### ISSUE TITLE
placerholders are not replaced

### ISSUE THREAD

**Issue by Fantus** [mariano/node-db-mysql#50] opened 2012-01-04 16:30 UTC
Tried it serveral times. copied the example from the website anyway its not working :(

console.log(connection.query()
                .update('map_value')
                .set({ 'last_used': "NOW()"})
                .where('id = ?', [id])
                .sql();
returns this
UPDATE `map_value` SET `last_used`='NOW()' WHERE id = ?

regards 
Fantus

**Comment by kmulvey** [comment] 2012-03-05 00:50
+1  .... would like this

**Comment by mariano** [comment] 2012-05-12 23:03
Duplicate of #49 and already answered there

**Closed as completed by mariano** 2012-05-12 23:03 UTC
