### ISSUE TITLE
Connection pool?

### ISSUE THREAD

**Issue by pplante** [mariano/node-db-mysql#7] opened 2011-05-28 08:06 UTC
Would it be possible to implement a connection pool, with a configurable number of connections, inside of the driver?  It would be great if we had an async connection pool to the db for queries.

**Comment by mariano** [comment] 2011-05-28 13:18
I've been thinking about it and most likely it will be implemented by the next release. I'll leave this ticket open until I do

**Comment by pplante** [comment] 2011-05-28 23:49
Thats great to hear.  I noticed there is no way to extend the Query class via javascript since it does not expose a **proto** object, do you have another way to accomplish this?  I have a few extra commands I would like to implement such as a method to exec "INSERT ... ON DUPLICATE KEY UPDATE" in one method call.  Right now I am building that part of the sql directly.

I love this library, thanks for taking the time to make it.

**Comment by mariano** [comment] 2011-05-31 15:26
@pplante: I'm going to commit something to db-mysql that I'd like you to test. I'm looking to solve the "prototype" problem for inheriting from Query you are facing, and going through the v8 mailing list has not helped me much, since this problem seems to puzzle most people.

So I'd request you to git clone from the db-mysql repo and build it, before you try it. Would you be willing to do that?

**Comment by pplante** [comment] 2011-05-31 15:28
I'm game.  Commit away!
On May 31, 2011 8:26 AM, "mariano" <
reply@reply.github.com>
wrote:

**Comment by mariano** [comment] 2011-05-31 15:32
Now that i'm looking at what I'm doing I don't think it helps much.

I am able to assign an object to "prototype" that contains all the template functions, so if you do console.log(db.query()) you get this:

```
{ prototype:                                                                                                                                                                                              
   { select: [Function: select],                                                                                                                                                                          
     from: [Function: from],                                                                                                                                                                              
     join: [Function: join],                                                                                                                                                                              
     where: [Function: where],                                                                                                                                                                            
     and: [Function: and],                                                                                                                                                                                
     or: [Function: or],                                                                                                                                                                                  
     order: [Function: order],                                                                                                                                                                            
     limit: [Function: limit],                                                                                                                                                                            
     add: [Function: add],                                                                                                                                                                                
     insert: [Function: insert],                                                                                                                                                                          
     update: [Function: update],                                                                                                                                                                          
     set: [Function: set],                                                                                                                                                                                
     delete: [Function: delete],                                                                                                                                                                          
     sql: [Function: sql],                                                                                                                                                                                
     execute: [Function: execute] } }
```

The problem is that if you then do something like:

```
db.query().prototype.test = function() { console.log("HELLO"); };
```

A subsequent console.log(db.query()) shows the query prototype unaltered.

Exporting the Query obviously doesn't help, since it is actually a function.

So I guess I have to keep thinking about this.

**Comment by mariano** [comment] 2011-05-31 15:36
Ok I think i figured it out. So you are going to have something for testing. Give me a sec.

**Comment by pplante** [comment] 2011-05-31 15:37
Okay thanks for the reply.  I see what you mean.  Is it possible to expose
the class without the need for .query()?
On May 31, 2011 8:32 AM, "mariano" <
reply@reply.github.com>
wrote:

**Comment by mariano** [comment] 2011-05-31 15:37
haha actually it works out of the box, without changing the C++ code, all I needed to do was export the Query

**Comment by pplante** [comment] 2011-05-31 15:44
Oh that's great.  Ill pull the changes later today and give them a shot.

**Comment by mariano** [comment] 2011-05-31 16:00
No need to use git, i decided to make a release since i'm also making the Query.execute() callback to run within the Query instance scope.

So update your db-mysql.

View the [Release announcement](http://nodejsdb.org/2011/05/node-db-0-6-3-released/) to see an example of how to extend Query.

**Comment by mariano** [comment] 2011-05-31 17:57
@pplante: regarding the other issue in this ticket (connection pooling.) I've been thinking about it, and I think engineering a generic pool mechanism right in node-db may be a bit overkill, not in the sense of effort, but in the sense of what the real purpose of node-db is.

Other generic pooling alternatives for node.js seem to be able to play with node-db without any issues, for example [node-pool](https://github.com/coopernurse/node-pool)

So I think I'm instead going to write a blog post on the node-db site showing how to use node-pool with node-db, and then close this ticket. Sounds good?

**Comment by mariano** [comment] 2011-05-31 18:37
Finished article showing [how to use generic-pool to do connection pooling of node-db connections](http://nodejsdb.org/2011/05/connection-pooling-node-db-with-generic-pool/)

**Closed as completed by mariano** 2011-05-31 18:37 UTC

**Comment by pplante** [comment] 2011-05-31 20:19
I think that's a good comprise.  Thanks for putting that together.
